# FOR REFERNCE OF DOCKER COMPOSE FILE
version: "3.8"
services:
  app:
      image: repo:tag
      restart: unless-stopped
      ports:
        - "3000:3000"
      environment:
        PORT: 3000
        NODE_ENV: production

        # -- URLs --
        PUBLIC_URL: http://localhost:3000
        STORAGE_URL: http://13.202.209.161:9000/default

        # -- Printer (Chrome) --
        CHROME_TOKEN: chrome_token
        CHROME_URL: ws://13.202.209.161:3000

        # -- Database (Postgres) --
        DATABASE_URL: postgresql://postgres:postgres@13.202.209.161:5432/postgres

        # -- Auth --
        ACCESS_TOKEN_SECRET: access_token_secret
        REFRESH_TOKEN_SECRET: refresh_token_secret

        # -- Emails --
        MAIL_FROM: noreply@localhost
        # SMTP_URL: smtp://user:pass@smtp:587 # Optional

        # -- Storage (Minio) --
        STORAGE_ENDPOINT: 13.202.209.161
        STORAGE_PORT: 9000
        # STORAGE_REGION: us-east-1 # Optional
        STORAGE_BUCKET: reactive-resume
        STORAGE_ACCESS_KEY: minioadmin
        STORAGE_SECRET_KEY: minioadmin
        STORAGE_USE_SSL: false
        STORAGE_SKIP_BUCKET_CHECK: false

        # -- Crowdin (Optional) --
        # CROWDIN_PROJECT_ID:
        # CROWDIN_PERSONAL_TOKEN:

        # -- Email (Optional) --
        # DISABLE_SIGNUPS: false
        # DISABLE_EMAIL_AUTH: false

        # -- GitHub (Optional) --
        # GITHUB_CLIENT_ID: github_client_id
        # GITHUB_CLIENT_SECRET: github_client_secret
        # GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback

        # -- Google (Optional) --
        # GOOGLE_CLIENT_ID: google_client_id
        # GOOGLE_CLIENT_SECRET: google_client_secret
        # GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback
